name: Run PHP Script

on:
  schedule:
    - cron: "20 13 * * *"
  workflow_dispatch:
    inputs:
      debug:
        description: "Run in debug mode (no email, print only)"
        required: false
        default: false
        type: boolean

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install Composer dependencies (if any)
        run: composer install

      - name: Run the PHP script
        env:
          GMAIL_SMTP_USER: ${{ secrets.GMAIL_SMTP_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          DEBUG_FLAG=""
            if [ "${{ github.event.inputs.debug }}" = "true" ]; then
              DEBUG_FLAG="--debug"
            fi

          php bin/run.php \
            --name="Kaz Schmanski" \
            --url="https://ultrasignup.com/event_waitlist.aspx?did=126417" \
            $DEBUG_FLAG
